### ISSUE TITLE
how can i establish connection ? 

### ISSUE THREAD

**Issue by flutter-painter** [BeMacized/xiaomi_scale#17]
Looks like a cool package !
I'm using a Xiaomi Smart Mi Scale 2,
I allowed Position and enable bluetooth but cannot go much further,
Is it necessary to connect the scale with the device using Xiaomi official app first ?
Thanks for any guidance

**Comment by flutter-painter** [comment]
Hi @BeMacized sorry to insist, but could you please provide a little bit guidance regarding connection ?

**Comment by BeMacized** [comment]
Hi, have you tried running the example app and does it give you the same issues, and if so, where does it get stuck for you? You should not have to connect it via the official app first. If the scale is powered and activated (stand on it for a few seconds), you should be able to see it when scanning for it using the example app.

**Comment by flutter-painter** [comment]
I fail to connect with the scal using android default bluetooth pairing,
Android system says sth in French like "doublecheck the device is visible to others"
So I presumed the only way to connect device via bluetooth was using official app or this lib,
But after following the tedious process it still does not detect a thing, tried with several smartphones,
I presume the brand new scale is not working as well as I hoped...

**Comment by flutter-painter** [comment]
here is the video in case anyone encounters same error : 
https://drive.google.com/file/d/1hxfQZfXfKNmG6fJoh14e2mz5kG6WVXvH/view?usp=sharing

**Comment by BeMacized** [comment]
@flutter-painter You shouldn't need to connect to the scale at all, especially not by trying to pair directly. All the scale data is in the advertisement data which is just picked up by scanning, no need for a connection. Either take a look at the included example app or follow the readme to get it working.

**Comment by BeMacized** [comment]
I do notice the model of your scale differs from your video now. I'm not sure why you seemingly cannot get it to work with the app from Xiaomi, but I can say that this plugin is currently only compatible with the Xiaomi Body Composition Scale 2. Yours seems to be lacking the electrodes on top, which makes me guess it's a different model.

**Comment by flutter-painter** [comment]
Thanks again for the quick answer,
**It actually works** by connecting the scale through redmi official app,
However using this pub it is still constantly loading,
I see no error, no dialog, no print and would like to understand why

Why not add in the readme just this : 'do not try to pair directly, do it through the app only' ?

**Comment by flutter-painter** [comment]
Yes, this was 1st assumption,
I'll retry with the appropriate one and keep you posted if succeeds,
cheers

**Comment by flutter-painter** [comment]
Hi @BeMacized,
Just tried on the right model and it works like a charm ! 
Thanks again for your support and merry christmas :)

**Comment by BeMacized** [comment]
That's good to hear! Merry christmas to you too :)
