### ISSUE TITLE
Add documentation for iOS & Android permission

### ISSUE THREAD

**Issue by vanlooverenkoen** [BeMacized/xiaomi_scale#5]
To using this package the readme should contain clear documentation what a developer should add for permissions. and where he should add it

**Comment by BeMacized** [comment]
Agreed! I can probably take a look at this on Friday.

**Comment by vanlooverenkoen** [comment]
Nice. Thanks.

**Comment by vanlooverenkoen** [comment]
https://github.com/PhilipsHue/flutter_reactive_ble/issues/89 Should add the documentation as well

**Comment by vanlooverenkoen** [comment]
Added in #6
